### ISSUE TITLE
Non-video planes rendered very dim

### ISSUE THREAD

**Issue by CiNcH83** [CiNcH83/bravia_atv2#59]
Everything except for hardware accelerated video is being rendered very dim. Affected are all UI elements like menus for example, but also software decoded video which does not go through the BRAVIA’s video processing pipeline.
 
This most probably is a measure to mitigate clouding on LCD in UIs to which no local dimming is applied. Problem is that text can be hard to read at times (e.g. daytime) and that colors are just off.
 
The difference becomes obvious with the following demo app:
![](https://www.dropbox.com/s/q3o8n2ko0fk1e4c/ui_dimness.jpg?raw=1)
 
To the right is a hardware accelerated video, to the left a UI element. Both are supposed to render the same red tone (#FF0000). The UI element is much dimmer though.

**Comment by S0und** [comment]
Same up running on a Oneplus 6T:

![image](https://user-images.githubusercontent.com/1266308/58471396-0f8a6c80-8144-11e9-920c-e8cbdff12887.png)

**Comment by Morac2** [comment]
From what I’ve been able to tell, this issue is specific to the 900F models as all reports have come from users who say they are using that model.  I have a 930e and menus are not any dimmer in 6.6510 than they were in the previous software.  I’ve had a number of 930e users confirm the same.

**Comment by S0und** [comment]
@Morac2 Thank you for clarification, hopefully this is just a bug.

**Comment by johnickz** [comment]
Same here KD65XF9005, 6.6510. SONY customer says that I restart the tv or factory reset which already made with no result at all. Dim brightness, dim colors at Menus, Playback through browsers, dim even at Chromecast. This is awfull. Contrast isn't taking any result at 0 or at Max.

**Comment by Morac2** [comment]
I’ve also read if you open an app such as the Google Play App Store, you can then adjust the menu brightness using the picture adjustment settings as a work around, though I can’t test that.

**Comment by johnickz** [comment]
You cant adjust anything there. I tried, thats why I state that Contrast isnt make any difference at all at 0 or Max. Only Gamma adding make the picture a little brighter but its far from what it has to be. Its like a grey filter cuting the 50% Brightness of the screen no matter what you ll change.

**Comment by stevex77** [comment]
I must agree that it has definitely someting to do with CONTRAST setting, not the brightness.

It seems like for Android UI elements / applications the contrast is FIXED at approx 37% (experimentally measured), that is significantly lower than 90% default, causing the peak white level to be really dim. The contrast remains constant, no matter if you set it to 0 or 100%, for every input (Digital TV, any HDMI, application, ...)

Contrast and black level settings only affect the HW video streams (both in-app and from external inputs like HDMIs).

It's a major problem for example in HBO GO application, where subtitles are rendered over the video layer, probably as a standard Android UI text and with this new firmware they are also low-contrast "grayish", instead of white, that draw them unreadable in many brighter scenes.

Observed on my xf9005 with current firmware 6.6510. No meaningful workaround found yet.

**Comment by S0und** [comment]
"Further delays for Asia/Pacific Oreo update

Had a live chat with Sony Australia support. Still no ETA. Again saying that their engineers are resolving further issues that are affecting users who got the latest update in US and Europe (no specifics on what these issues are however)."

I'm really hoping that those "further issues" includes this. This was a post from /r/bravia

**Comment by CiNcH83** [comment]
Fixed with FW 6.6520.
